ALTER TABLE submissions
  ADD COLUMN IF NOT EXISTS status VARCHAR(40),
  ADD COLUMN IF NOT EXISTS error_message TEXT,
  ADD COLUMN IF NOT EXISTS stderr TEXT,
  ADD COLUMN IF NOT EXISTS error_line INTEGER,
  ADD COLUMN IF NOT EXISTS runtime_ms INTEGER,
  ADD COLUMN IF NOT EXISTS memory_kb INTEGER;
